"""redefine relationship betewen user and team

Revision ID: 077edaec6502
Revises: 3e5e119dede5
Create Date: 2023-09-03 02:26:30.783697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "077edaec6502"
down_revision = "3e5e119dede5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            None, "user", ["leader_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("team_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None, "team", ["team_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("team_id")

    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["leader_id"], ["id"])

    # ### end Alembic commands ###
