"""add name column to User

Revision ID: 180153b10507
Revises: 1383a9205050
Create Date: 2023-09-03 00:11:28.585247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "180153b10507"
down_revision = "1383a9205050"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name", sa.String(length=128), server_default="?", nullable=False)
        )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("name", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
