"""fix missing recordid for comments

Revision ID: 35e4d07c6513
Revises: 7ec2db418071
Create Date: 2023-10-15 00:08:10.308482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e4d07c6513'
down_revision = '7ec2db418071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_record_record'), 'record', ['record'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_record_record'), type_='foreignkey')
        batch_op.drop_column('record')

    # ### end Alembic commands ###
