"""team in records

Revision ID: 642ec868d46a
Revises: 
Create Date: 2023-09-18 19:22:55.326729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642ec868d46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_record')
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_record_team_id_team'), 'team', ['team_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_record_team_id_team'), type_='foreignkey')
        batch_op.drop_column('team_id')

    op.create_table('_alembic_tmp_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=192), nullable=True),
    sa.Column('subsystem_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('impact', sa.TEXT(), nullable=True),
    sa.Column('cause', sa.TEXT(), nullable=True),
    sa.Column('mechanism', sa.TEXT(), nullable=True),
    sa.Column('corrective_action_plan', sa.TEXT(), nullable=True),
    sa.Column('time_of_failure', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('modified_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('car_year', sa.INTEGER(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='fk_record_creator_id_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subsystem_id'], ['subsystem.id'], name='fk_record_subsystem_id_subsystem', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='fk_record_team_id_team', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_record')
    )
    # ### end Alembic commands ###
