"""fix missing recordid for comments

Revision ID: 79ea28ee2bb3
Revises: 7ae98add553f
Create Date: 2023-10-15 00:19:07.256713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ea28ee2bb3'
down_revision = '7ae98add553f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comment_record_id_record'), 'record', ['record_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_record_id_record'), type_='foreignkey')
        batch_op.drop_column('record_id')

    # ### end Alembic commands ###
