"""fix missing recordid for comments

Revision ID: 7ae98add553f
Revises: 35e4d07c6513
Create Date: 2023-10-15 00:10:03.719629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae98add553f'
down_revision = '35e4d07c6513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_record_record', type_='foreignkey')
        batch_op.drop_column('record')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comment_record_record', 'record', ['record'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
