"""empty message

Revision ID: b11bd9c1f16a
Revises: d310dfd52b3c
Create Date: 2023-10-02 14:00:37.456180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11bd9c1f16a'
down_revision = 'd310dfd52b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_record',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('fk_user_record_record_id_record')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_record_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'record_id', name=op.f('pk_user_record'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_record')
    # ### end Alembic commands ###
