"""add comments

Revision ID: d92c480219fb
Revises: b11bd9c1f16a
Create Date: 2023-10-14 23:11:52.301371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92c480219fb'
down_revision = 'b11bd9c1f16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
